### ISSUE TITLE
Markdown editor for posts

### ISSUE THREAD

**Issue by tomaszmalik** [rayrfan/Fanray#370]
It's seems that markdown editor is used only for pages.
It would be great if this could be an option for creating posts too!
Actually I need only markdown editor, so if I had to switch it config and have only markdown editor, it would be fine.
What do you think? :)

**Comment by rayrfan** [comment]
@tomaszmalik I agree it could be useful to let user choose the editor they want to use, I know there are some people prefer one editor over the other.

To give you a little background, I released v1 as an MVP in which I supported only blog posts. And the only option to write posts in v1 was using Open Live Writer, I did not have an admin panel till v1.1.  OLW is HTML only, so when I started v1.1 I had to continue to support HTML for writing posts, and this is how I chose a rich text editor for that. It's not until I started working on Pages that I had the chance to bring in a markdown editor, and I decided not to support authoring pages from OLW. 

Here is one issue to consider, converting from Markdown to HTML is reliable, but HTML to Markdown is not! This potentially is problematic if we give the user the ability to choose between a Rich Text and Markdown editor. So to support this feature we have to 

1. Warn users that once you decide on an editor whether rich text or markdown, the content you author with that editor cannot be edited later with the other editor.
2. Add extra logic in admin panel and olw to filter posts appropriate for the that editor only.

To be complete, I do want to point out the content written with markdown editor can be edited later with rich text editor, but once user makes changes he cannot go back to markdown editor anymore.

I had these thoughts in the past but thought to myself the user experience could be confusing for the undertaking it takes to implement. I thank you for bringing this up and I'd like to hear from you and others on your thoughts. And if this is indeed something the community wants, we can open up a branch and give it a stab.
